// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFPI3GFcttCRsGGqi4PFXXxKsiju4QyCc',
    appId: '1:324322083796:web:112439045e635cb1d7cc41',
    messagingSenderId: '324322083796',
    projectId: 'dancamais-1c057',
    authDomain: 'dancamais-1c057.firebaseapp.com',
    storageBucket: 'dancamais-1c057.firebasestorage.app',
    measurementId: 'G-2LTTK4T3F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzNMA6J3VLxoubvT3Wd78QnzBjUaBo7bQ',
    appId: '1:324322083796:android:9c84cb9694a20aebd7cc41',
    messagingSenderId: '324322083796',
    projectId: 'dancamais-1c057',
    storageBucket: 'dancamais-1c057.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE8sRgU8fEcybXRTKkuq8hs_Ss-34QK7w',
    appId: '1:324322083796:ios:cee18d9876bdf953d7cc41',
    messagingSenderId: '324322083796',
    projectId: 'dancamais-1c057',
    storageBucket: 'dancamais-1c057.firebasestorage.app',
    iosBundleId: 'com.example.dancamais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE8sRgU8fEcybXRTKkuq8hs_Ss-34QK7w',
    appId: '1:324322083796:ios:cee18d9876bdf953d7cc41',
    messagingSenderId: '324322083796',
    projectId: 'dancamais-1c057',
    storageBucket: 'dancamais-1c057.firebasestorage.app',
    iosBundleId: 'com.example.dancamais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFPI3GFcttCRsGGqi4PFXXxKsiju4QyCc',
    appId: '1:324322083796:web:68de2708a375660ad7cc41',
    messagingSenderId: '324322083796',
    projectId: 'dancamais-1c057',
    authDomain: 'dancamais-1c057.firebaseapp.com',
    storageBucket: 'dancamais-1c057.firebasestorage.app',
    measurementId: 'G-7GQB5F619T',
  );

}